add option to build with or without doubledown
conda-forge/dagmc-feedstock pull request #30
Opened 2024-09-27 14:35 UTC by bquan0

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

I added a variable in `conda_build_config.yaml` for `doubledown` and modified `build.sh` and `meta.yaml` to allow packages to be built with or without `doubledown`.

2024-09-27 14:37 UTC, bquan0 commented
@conda-forge-admin, please rerender

2024-09-27 21:05 UTC, bquan0 commented
@conda-forge-admin, please rerender

2024-09-28 09:03 UTC, shimwell commented
It would be great to include doubledown

I thought it was not available on conda so that might need fixing first.

Here is the related issue

https://github.com/pshriwise/double-down/issues/31

2024-10-05 15:21 UTC, gonuke requested changes
I think it needs more help to find double down

2024-10-05 15:21 UTC, gonuke commented on recipe/build.sh
> -      -DDOUBLE_DOWN=OFF \
I think you need to specify the location of double down:
```
        -Ddd_ROOT=${PREFIX} && \
```

2024-10-05 22:07 UTC, bquan0 commented
@conda-forge-admin, please rerender

2024-10-05 22:30 UTC, bquan0 commented
After specifying the location of double down and rerendering the feedstock since I changed the name of the double down variable to `dd`, all tests are now passing.

2024-10-05 22:41 UTC, gonuke commented
When I look at the tests, I don't see any evidence that this was built with double down.  I think it's because it's using v3.2.3 and the CMake configuration is out of date relative to `develop`.  Maybe we need to issue another release of DAGMC.

2024-10-08 16:12 UTC, pshriwise commented
@gonuke, @bquan0 and I touched base this morning. As a short term solution I suggested verbose output from one of the tests which will show whether or not double down is enabled in the output:

```
1: Using the DOUBLE-DOWN interface to Embree.
1: Loading file test_dagmc_impl.h5m
1: Initializing the GeomQueryTool...
1: Using faceting tolerance: 0.001
1: Building acceleration data structures...
```

In the long term, for partial verification we certainly should add some output from DAGMC that double down is enabled during the configuration step.

2024-11-27 08:46 UTC, shimwell commented
> In the long term, for partial verification we certainly should add some output from DAGMC that double down is enabled during the configuration step.

I really like this feature that @gridley added to OpenMC.
```bash
$ openmc --version
OpenMC version 0.15.0
Git SHA1: 84fb85977f46e162fea8f5a20ea653a3ec62ac24
Copyright (c) 2011-2024 MIT, UChicago Argonne LLC, and contributors
MIT/X license at <https://docs.openmc.org/en/latest/license.html>
Build type:            Release
Compiler ID:           GNU 12.3.0
MPI enabled:           yes
Parallel HDF5 enabled: yes
PNG support:           yes
DAGMC support:         yes
libMesh support:       no
MCPL support:          no
NCrystal support:      no
Coverage testing:      no
Profiling flags:       no
UWUW support:          no
```

Perhaps we could expanded it to include Double_Down_support details on the DAGMC aspect like this
```bash
$ openmc --version
OpenMC version 0.15.0
Git SHA1: 84fb85977f46e162fea8f5a20ea653a3ec62ac24
Copyright (c) 2011-2024 MIT, UChicago Argonne LLC, and contributors
MIT/X license at <https://docs.openmc.org/en/latest/license.html>
Build type:            Release
Compiler ID:           GNU 12.3.0
MPI enabled:           yes
Parallel HDF5 enabled: yes
PNG support:           yes
DAGMC support:         yes
    Embree_support: yes
    Double_Down_support: yes
libMesh support:       no
MCPL support:          no
NCrystal support:      no
Coverage testing:      no
Profiling flags:       no
UWUW support:          no
```

2025-01-28 15:58 UTC, merged